In [4]:
import yfinance as yf
import pandas as pd

In [3]:
msft = yf.Ticker("MSFT")

In [7]:
fast_info = msft.fast_info
fast_info

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']

In [8]:
history = msft.history(period="max") # period = "1mo"
history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13 00:00:00-05:00,0.055241,0.063365,0.055241,0.060657,1031788800,0.0,0.0
1986-03-14 00:00:00-05:00,0.060657,0.063907,0.060657,0.062823,308160000,0.0,0.0
1986-03-17 00:00:00-05:00,0.062823,0.064448,0.062823,0.063907,133171200,0.0,0.0
1986-03-18 00:00:00-05:00,0.063907,0.064448,0.061740,0.062281,67766400,0.0,0.0
1986-03-19 00:00:00-05:00,0.062281,0.062823,0.060657,0.061198,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2023-03-01 00:00:00-05:00,250.759995,250.929993,245.789993,246.270004,27565300,0.0,0.0
2023-03-02 00:00:00-05:00,246.550003,251.399994,245.610001,251.110001,24808200,0.0,0.0
2023-03-03 00:00:00-05:00,252.190002,255.619995,251.389999,255.289993,30741300,0.0,0.0
2023-03-06 00:00:00-05:00,256.429993,260.119995,255.979996,256.869995,24088400,0.0,0.0
2023-03-07 00:00:00-05:00,256.299988,257.679993,256.059998,257.084991,2587072,0.0,0.0

In [9]:
history_metadata = msft.history_metadata
history_metadata

{'currency': 'USD',
 'symbol': 'MSFT',
 'exchangeName': 'NMS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': Timestamp('1986-03-13 09:30:00-0500', tz='America/New_York'),
 'regularMarketTime': Timestamp('2023-03-07 09:58:10-0500', tz='America/New_York'),
 'gmtoffset': -18000,
 'timezone': 'EST',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 257.085,
 'chartPreviousClose': 0.097,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'start': Timestamp('2023-03-07 04:00:00-0500', tz='America/New_York'),
   'end': Timestamp('2023-03-07 09:30:00-0500', tz='America/New_York')},
  'regular': {'start': Timestamp('2023-03-07 09:30:00-0500', tz='America/New_York'),
   'end': Timestamp('2023-03-07 16:00:00-0500', tz='America/New_York')},
  'post': {'start': Timestamp('2023-03-07 16:00:00-0500', tz='America/New_York'),
   'end': Timestamp('2023-03-07 20:00:00-0500', tz='America/New_York')}},
 'dataGranularity': '1d',
 'range': '',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [10]:
actions = msft.actions
actions

                           Dividends  Stock Splits
Date
1987-09-21 00:00:00-04:00       0.00           2.0
1990-04-16 00:00:00-04:00       0.00           2.0
1991-06-27 00:00:00-04:00       0.00           1.5
1992-06-15 00:00:00-04:00       0.00           1.5
1994-05-23 00:00:00-04:00       0.00           2.0
...                              ...           ...
2022-02-16 00:00:00-05:00       0.62           0.0
2022-05-18 00:00:00-04:00       0.62           0.0
2022-08-17 00:00:00-04:00       0.62           0.0
2022-11-16 00:00:00-05:00       0.68           0.0
2023-02-15 00:00:00-05:00       0.68           0.0

[86 rows x 2 columns]

In [11]:
dividends = msft.dividends
dividends

Date
2003-02-19 00:00:00-05:00    0.08
2003-10-15 00:00:00-04:00    0.16
2004-08-23 00:00:00-04:00    0.08
2004-11-15 00:00:00-05:00    3.08
2005-02-15 00:00:00-05:00    0.08
                             ...
2022-02-16 00:00:00-05:00    0.62
2022-05-18 00:00:00-04:00    0.62
2022-08-17 00:00:00-04:00    0.62
2022-11-16 00:00:00-05:00    0.68
2023-02-15 00:00:00-05:00    0.68
Name: Dividends, Length: 77, dtype: float64

In [12]:
splits = msft.splits
splits

Date
1987-09-21 00:00:00-04:00    2.0
1990-04-16 00:00:00-04:00    2.0
1991-06-27 00:00:00-04:00    1.5
1992-06-15 00:00:00-04:00    1.5
1994-05-23 00:00:00-04:00    2.0
1996-12-09 00:00:00-05:00    2.0
1998-02-23 00:00:00-05:00    2.0
1999-03-29 00:00:00-05:00    2.0
2003-02-18 00:00:00-05:00    2.0
Name: Stock Splits, dtype: float64

In [13]:
capital_gains = msft.capital_gains
capital_gains

[]

In [24]:
# - accurate time-series count:
msft.get_shares_full(start="2022-01-01", end=None)

2022-01-27 00:00:00-05:00    7496869888
2022-02-04 00:00:00-05:00    7800719872
2022-02-05 00:00:00-05:00    7496869888
2022-02-11 00:00:00-05:00    7496869888
2022-03-04 00:00:00-05:00    7605040128
2022-03-05 00:00:00-05:00    7496869888
2022-03-16 00:00:00-04:00    7595310080
2022-03-17 00:00:00-04:00    7496869888
2022-03-28 00:00:00-04:00    7507230208
2022-03-31 00:00:00-04:00    7496869888
2022-04-01 00:00:00-04:00    7631819776
2022-04-02 00:00:00-04:00    7496869888
2022-04-04 00:00:00-04:00    7496869888
2022-04-29 00:00:00-04:00    7479029760
2022-06-09 00:00:00-04:00    7536840192
2022-06-13 00:00:00-04:00    7479029760
2022-07-28 00:00:00-04:00    7464000000
2022-08-01 00:00:00-04:00    7457889792
2022-08-25 00:00:00-04:00    7475469824
2022-08-26 00:00:00-04:00    7457889792
2022-09-01 00:00:00-04:00    7457889792
2022-09-02 00:00:00-04:00    7488540160
2022-09-02 00:00:00-04:00    7457889792
2022-09-10 00:00:00-04:00    7290379776
2022-09-12 00:00:00-04:00    7457889792
2022-09-15 00:00:00-04:00    7451089920
2022-09-15 00:00:00-04:00    7457889792
2022-09-16 00:00:00-04:00    7665780224
2022-09-16 00:00:00-04:00    7457889792
2022-09-17 00:00:00-04:00    7457889792
2022-09-17 00:00:00-04:00    7477389824
2022-10-29 00:00:00-04:00    7454470144
2023-01-04 00:00:00-05:00    7461940224
2023-01-06 00:00:00-05:00    7454470144
2023-01-27 00:00:00-05:00    7443800064
dtype: int64

In [31]:
msft.major_holders

        0                                      1
0   0.06%        % of Shares Held by All Insider
1  73.70%       % of Shares Held by Institutions
2  73.74%        % of Float Held by Institutions
3    6152  Number of Institutions Holding Shares

In [32]:
msft.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",642664898,2022-12-30,0.0863,164978500474
1,Blackrock Inc.,532042708,2022-12-30,0.0715,136580679024
2,State Street Corporation,294574683,2022-12-30,0.0396,75620264355
3,"FMR, LLC",198985661,2022-12-30,0.0267,51081607334
4,Price (T.Rowe) Associates Inc,168647376,2022-12-30,0.0227,43293466451
5,"Geode Capital Management, LLC",142731177,2022-12-30,0.0192,36640519228
6,Morgan Stanley,119417954,2022-12-30,0.0160,30655781950
7,JP Morgan Chase & Company,93021058,2022-12-30,0.0125,23879435004
8,Capital World Investors,91715063,2022-12-30,0.0123,23544173039
9,Norges Bank Investment Management,86316926,2022-12-30,0.0116,22158417335

In [33]:
msft.mutualfund_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Total Stock Market Index Fund,222313847,2022-09-29,0.0299,57070185763
1,Vanguard 500 Index Fund,169062762,2022-09-29,0.0227,43400100188
2,SPDR S&P 500 ETF Trust,82250000,2022-12-30,0.0110,21114396797
3,Fidelity 500 Index Fund,81679555,2022-12-30,0.0110,20967957866
4,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",76335623,2022-12-30,0.0103,19596117128
5,iShares Core S&P 500 ETF,66940817,2022-12-30,0.0090,17184376560
6,Vanguard Growth Index Fund,61426549,2022-09-29,0.0083,15768808868
7,Vanguard Institutional Index Fund-Institutiona...,54149972,2022-09-29,0.0073,13900838849
8,Growth Fund Of America Inc,44491127,2022-12-30,0.0060,11421316831
9,Select Sector SPDR Fund-Technology,34910084,2022-12-30,0.0047,8961767365

In [40]:
# following analysts recommendations NOT FOUND!!!!
msft.recommendations
msft.recommendations_summary
# show analysts other work
msft.analyst_price_target
msft.revenue_forecasts
msft.earnings_forecasts
msft.earnings_trend

In [45]:
# show next event (earnings, etc)
print(msft.calendar)

None

In [46]:
# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2024-01-22 16:00:00-05:00           NaN           NaN          NaN
2024-01-22 05:00:00-05:00           NaN           NaN          NaN
2023-10-23 06:00:00-04:00           NaN           NaN          NaN
2023-07-24 06:00:00-04:00           NaN           NaN          NaN
2023-04-24 06:00:00-04:00          2.23           NaN          NaN
2023-01-24 11:00:00-05:00          2.30          2.32       0.0109
2022-10-25 12:00:00-04:00          2.30          2.35       0.0204
2022-07-26 12:00:00-04:00          2.29          2.23      -0.0275
2022-04-26 12:00:00-04:00          2.19          2.22       0.0160
2022-01-25 11:00:00-05:00          2.31          2.48       0.0727
2021-10-26 12:00:00-04:00          2.08          2.27       0.0940
2021-07-27 12:00:00-04:00          1.92          2.17       0.1326

In [48]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

None

In [49]:
# show options expirations
msft.options

('2023-03-10',
 '2023-03-17',
 '2023-03-24',
 '2023-03-31',
 '2023-04-06',
 '2023-04-14',
 '2023-04-21',
 '2023-05-19',
 '2023-06-16',
 '2023-07-21',
 '2023-08-18',
 '2023-09-15',
 '2023-10-20',
 '2024-01-19',
 '2024-06-21',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-12-19')

In [50]:
# show news
msft.news

[{'uuid': 'c2aa419c-bdb6-310f-80cf-d6e1fe2c2acd',
  'title': 'Dow Jones Futures: Will Powell Testimony Threaten Stock Market Rally? Apple, Tesla In Focus',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/c2aa419c-bdb6-310f-80cf-d6e1fe2c2acd/dow-jones-futures%3A-will.html',
  'providerPublishTime': 1678193575,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/NxDqCmJ2e.IKfjRDXxAYUg--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/799b09e1a8248a8ff634375e531e258e',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/oLZVcszDFZ6XLXX32T8xrw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/799b09e1a8248a8ff634375e531e258e',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA', '^DJI', 'AYX', 'ANET', 'MSFT']},
 {'uuid': 'bf78767a-8842-3236-b0c1-f513b9ad8c03',
  'title': 'Why C3.ai Stock Gained 14% in February',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/bf78767a-8842-3236-b0c1-f513b9ad8c03/why-c3.ai-stock-gained-14%25-in.html',
  'providerPublishTime': 1678189589,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/p3f4sP.g3bcWWmP4pChLcA--~B/aD01NzczO3c9ODY2MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/f3238acb1bfdb64f42af0150721e0adc',
     'width': 8660,
     'height': 5773,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/hZiWvwsYiFlb3uoTEAMcMg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/f3238acb1bfdb64f42af0150721e0adc',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AI', 'MSFT', 'GOOGL']},
 {'uuid': '427dfef7-6265-3bbd-b5bf-ee703fd9bcb6',
  'title': 'Sceptical investors worry whether advances in AI will make money',
  'publisher': 'Financial Times',
  'link': 'https://finance.yahoo.com/m/427dfef7-6265-3bbd-b5bf-ee703fd9bcb6/sceptical-investors-worry.html',
  'providerPublishTime': 1678165210,
  'type': 'STORY',
  'relatedTickers': ['MSFT']},
 {'uuid': '7b9a93ce-4461-300b-babb-14e2fdda1273',
  'title': 'Microsoft Targets Enterprise Application Players Oracle, Salesforce, SAP With Latest AI Offerings',
  'publisher': 'Benzinga',
  'link': 'https://finance.yahoo.com/news/microsoft-targets-enterprise-application-players-213232709.html',
  'providerPublishTime': 1678138352,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/UwVXTrIOdyI8WOqiiTAypw--~B/aD00MDA7dz02MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Benzinga/5df4c5ee95be18f4057d39b1be836baa',
     'width': 600,
     'height': 400,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/mx36Q25dwg.C5mzu92wFYw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/5df4c5ee95be18f4057d39b1be836baa',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'CRM', 'GOOGL', 'ORCL']},
 {'uuid': '6d8dcc81-1142-373e-97bf-9846b1cb7c72',
  'title': '2 Stocks These GuruFocus Value Conference Speakers Agree On',
  'publisher': 'GuruFocus.com',
  'link': 'https://finance.yahoo.com/news/2-stocks-gurufocus-value-conference-193821563.html',
  'providerPublishTime': 1678131501,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/kOxof1g4Wb_2EUj2W586_A--~B/aD0zNjY7dz01NTA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/us.finance.gurufocus/99f00e58761834ab4b9e8c4e08e4f810',
     'width': 550,
     'height': 366,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/Kkk3cCFDq6.pYqw1V.135g--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/us.finance.gurufocus/99f00e58761834ab4b9e8c4e08e4f810',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['UNH', 'MSFT']},
 {'uuid': 'f4b702f8-d32c-46b0-b032-418b3a33bbf1',
  'title': 'Why Appleâ€™s headset could seriously boost the flagging VR market',
  'publisher': 'Yahoo Finance',
  'link': 'https://finance.yahoo.com/news/why-apples-headset-could-seriously-boost-the-flagging-vr-market-192922101.html',
  'providerPublishTime': 1678130962,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Tv2zOFRvU9XAfAEL1F6S7w--~B/aD0zMzM0O3c9NTAwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2022-11/a53a9df0-6155-11ed-bd1b-b0029a02c734',
     'width': 5000,
     'height': 3334,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/Inr79LfHC_AwGv4Qb9IGGw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2022-11/a53a9df0-6155-11ed-bd1b-b0029a02c734',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AAPL', 'MSFT']},
 {'uuid': '8994c7f3-146e-49c6-b3e4-992558c80200',
  'title': 'Apple stock jumps as Goldman Sachs puts Buy rating on stock',
  'publisher': 'Yahoo Finance',
  'link': 'https://finance.yahoo.com/news/apple-stock-jumps-as-goldman-sachs-puts-buy-rating-on-stock-191123444.html',
  'providerPublishTime': 1678129897,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ml8xwVs7nMj0hrcYh3bSdw--~B/aD0yNjY3O3c9NDAwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-02/e24a45b0-bc4f-11ed-a7d7-66612a1d89d1',
     'width': 4000,
     'height': 2667,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/PuontGj5TQDcIT8k56AsjA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2023-02/e24a45b0-bc4f-11ed-a7d7-66612a1d89d1',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOG', 'GOOGL', 'AMZN', 'MSFT', 'AAPL', 'META']},
 {'uuid': '57a90508-3d5c-3865-8def-592e220be109',
  'title': 'UPDATE 1-Microsoft integrates AI behind ChatGPT to more developer tools',
  'publisher': 'Reuters',
  'link': 'https://finance.yahoo.com/news/1-microsoft-integrates-ai-behind-184401803.html',
  'providerPublishTime': 1678128241,
  'type': 'STORY',
  'relatedTickers': ['MSFT']}]